package ZCS::Admin::Types::Right;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'urn:zimbraAdmin' };

our $XML_ATTRIBUTE_CLASS = 'ZCS::Admin::Types::Right::_Right::XmlAttr';

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}



# There's no variety - empty complexType
use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

__PACKAGE__->_factory();


package ZCS::Admin::Types::Right::_Right::XmlAttr;
use base qw(SOAP::WSDL::XSD::Typelib::AttributeSet);

{ # BLOCK to scope variables

my %deny_of :ATTR(:get<deny>);
my %canDelegate_of :ATTR(:get<canDelegate>);
my %subDomain_of :ATTR(:get<subDomain>);

__PACKAGE__->_factory(
    [ qw(
        deny
        canDelegate
        subDomain
    ) ],
    {

        deny => \%deny_of,

        canDelegate => \%canDelegate_of,

        subDomain => \%subDomain_of,
    },
    {
        deny => 'ZCS::Admin::Types::IntBool',
        canDelegate => 'ZCS::Admin::Types::IntBool',
        subDomain => 'ZCS::Admin::Types::IntBool',
    }
);

} # end BLOCK



1;


=pod

=head1 NAME

ZCS::Admin::Types::Right

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
Right from the namespace urn:zimbraAdmin.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over



=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

,



=head2 attr

NOTE: Attribute documentation is experimental, and may be inaccurate.
See the correspondent WSDL/XML Schema if in question.

This class has additional attributes, accessibly via the C<attr()> method.

attr() returns an object of the class ZCS::Admin::Types::Right::_Right::XmlAttr.

The following attributes can be accessed on this object via the corresponding
get_/set_ methods:

=over

=item * deny



This attribute is of type L<ZCS::Admin::Types::IntBool|ZCS::Admin::Types::IntBool>.

=item * canDelegate



This attribute is of type L<ZCS::Admin::Types::IntBool|ZCS::Admin::Types::IntBool>.

=item * subDomain



This attribute is of type L<ZCS::Admin::Types::IntBool|ZCS::Admin::Types::IntBool>.


=back




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

