
package ZCS::Admin::Elements::GrantRightRequest;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'urn:zimbraAdmin' }

__PACKAGE__->__set_name('GrantRightRequest');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %target_of :ATTR(:get<target>);
my %grantee_of :ATTR(:get<grantee>);
my %right_of :ATTR(:get<right>);

__PACKAGE__->_factory(
    [ qw(        target
        grantee
        right

    ) ],
    {
        'target' => \%target_of,
        'grantee' => \%grantee_of,
        'right' => \%right_of,
    },
    {
        'target' => 'ZCS::Admin::Types::GrantTarget',
        'grantee' => 'ZCS::Admin::Types::Grantee',
        'right' => 'ZCS::Admin::Types::Right',
    },
    {

        'target' => 'target',
        'grantee' => 'grantee',
        'right' => 'right',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

ZCS::Admin::Elements::GrantRightRequest

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GrantRightRequest from the namespace urn:zimbraAdmin.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * target

 $element->set_target($data);
 $element->get_target();




=item * grantee

 $element->set_grantee($data);
 $element->get_grantee();




=item * right

 $element->set_right($data);
 $element->get_right();





=back


=head1 METHODS

=head2 new

 my $element = ZCS::Admin::Elements::GrantRightRequest->new($data);

Constructor. The following data structure may be passed to new():

 {
   target => ,
   grantee => ,
   right => ,
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

